#!/usr/bin/env python
"""Render a pooled Stage-B result JSON into a CSV + LaTeX table under reports/tables/.

Reads the output of run_stage_b_all.py (outputs/anomaly-pipeline/_pooled/<run_tag>.json)
and writes a per-scenario table with MACRO (mean of per-scenario AUROC, UMAD-style)
and MICRO (all-pixels-pooled) summary rows. The macro mean is the headline; the micro
number is shown for completeness (it is dominated by the largest-anomaly scenarios).

Usage:
    external/Vista/.venv/bin/python scripts/make_report_tables.py \\
        outputs/anomaly-pipeline/_pooled/mse_ssim_pd_td__sam.json
"""

from __future__ import annotations

import argparse
import csv
import json
import os

import numpy as np

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

COLUMNS = [
    "scenario", "n_eval_frames", "n_anomaly_pixels",
    "pixel_auroc", "pixel_ap", "refined_auroc", "refined_ap",
]


def build_rows(d: dict) -> list[dict]:
    ps = d["per_scenario"]
    rows: list[dict] = []
    for s in ps:
        rows.append({
            "scenario": s["scenario_tag"],
            "n_eval_frames": s["n_eval_frames"],
            "n_anomaly_pixels": s["n_anomaly_pixels_pooled"],
            "pixel_auroc": s["pixel_auroc"],
            "pixel_ap": s["pixel_ap"],
            "refined_auroc": s["refined_auroc"],
            "refined_ap": s["refined_ap"],
        })

    def macro(key):
        vals = np.array([s[key] for s in ps if s[key] is not None], dtype=float)
        vals = vals[~np.isnan(vals)]
        return float(vals.mean()) if vals.size else float("nan")

    total_frames = sum(s["n_eval_frames"] for s in ps)
    total_px = sum(s["n_anomaly_pixels_pooled"] for s in ps)
    rows.append({
        "scenario": "MACRO_mean", "n_eval_frames": total_frames,
        "n_anomaly_pixels": total_px,
        "pixel_auroc": macro("pixel_auroc"), "pixel_ap": macro("pixel_ap"),
        "refined_auroc": macro("refined_auroc"), "refined_ap": macro("refined_ap"),
    })
    pm = d["pooled_pixel_metrics"]
    rm = d.get("pooled_refined_metrics") or {}
    rows.append({
        "scenario": "MICRO_pooled", "n_eval_frames": total_frames,
        "n_anomaly_pixels": d["n_anomaly_pixels_pooled"],
        "pixel_auroc": pm["auroc"], "pixel_ap": pm["ap"],
        "refined_auroc": rm.get("auroc"), "refined_ap": rm.get("ap"),
    })
    return rows


def fmt(v, nd=4) -> str:
    if v is None or (isinstance(v, float) and np.isnan(v)):
        return "--"
    if isinstance(v, float):
        return f"{v:.{nd}f}"
    return str(v)


def write_csv(rows: list[dict], path: str) -> None:
    with open(path, "w", newline="") as fh:
        w = csv.DictWriter(fh, fieldnames=COLUMNS)
        w.writeheader()
        for r in rows:
            w.writerow({k: (fmt(r[k]) if "auroc" in k or "_ap" in k else r[k])
                        for k in COLUMNS})


def write_latex(rows: list[dict], path: str, d: dict) -> None:
    run_tag = d["run_tag"]
    header = ("Scenario & Frames & Anom.\\,px & Pixel AUROC & Pixel AP & "
              "Refined AUROC & Refined AP \\\\")
    lines = [
        "% Generated by scripts/make_report_tables.py -- do not edit by hand.",
        "\\begin{table}[t]",
        "\\centering",
        f"\\caption{{Stage-B anomaly-detection results on the 16-scenario AnoVox "
        f"benchmark (run \\texttt{{{run_tag.replace('_', chr(92) + '_')}}}, "
        f"weights \\texttt{{{d['weights'].replace('_', chr(92) + '_')}}}, "
        f"SAM \\texttt{{{(d.get('aggregate') or 'n/a')}}}, eval-stride "
        f"{d['eval_stride']}). MACRO = mean of per-scenario AUROC (UMAD convention, "
        f"headline); MICRO = all pixels pooled into one ROC.}}",
        f"\\label{{tab:stageb-{run_tag.replace('_', '-')}}}",
        "\\begin{tabular}{lrrrrrr}",
        "\\toprule",
        header,
        "\\midrule",
    ]
    n_scn = len(d["per_scenario"])
    for i, r in enumerate(rows):
        tag = r["scenario"].replace("_", r"\_")
        if i == n_scn:  # first summary row -> rule above it
            lines.append("\\midrule")
        if r["scenario"] in ("MACRO_mean", "MICRO_pooled"):
            tag = f"\\textbf{{{tag}}}"
        lines.append(
            f"{tag} & {r['n_eval_frames']} & {r['n_anomaly_pixels']:,} & "
            f"{fmt(r['pixel_auroc'])} & {fmt(r['pixel_ap'])} & "
            f"{fmt(r['refined_auroc'])} & {fmt(r['refined_ap'])} \\\\"
        )
    lines += ["\\bottomrule", "\\end{tabular}", "\\end{table}", ""]
    with open(path, "w") as fh:
        fh.write("\n".join(lines))


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("pooled_json", help="path to _pooled/<run_tag>.json")
    ap.add_argument("--out-dir", default=os.path.join(REPO, "reports", "tables"))
    args = ap.parse_args()

    with open(args.pooled_json) as fh:
        d = json.load(fh)
    rows = build_rows(d)
    os.makedirs(args.out_dir, exist_ok=True)
    stem = d["run_tag"]
    csv_path = os.path.join(args.out_dir, f"{stem}.csv")
    tex_path = os.path.join(args.out_dir, f"{stem}.tex")
    write_csv(rows, csv_path)
    write_latex(rows, tex_path, d)
    print(f"wrote {csv_path}")
    print(f"wrote {tex_path}")
    return 0


if __name__ == "__main__":
    import sys
    sys.exit(main())
